-- Schema proposto para metricas anonimas/agregadas de utilizacao da CompY.
-- Nao executar em producao sem revisao tecnica institucional.
-- Nao guarda medicamentos selecionados, pares exatos, texto livre, IP, utilizadores
-- ou identificadores de doente/profissional.

begin;

create table if not exists public.usage_events (
  id bigint generated by default as identity primary key,
  event_name text not null check (
    event_name in (
      'app_open',
      'analysis_run',
      'alert_expanded',
      'base_status_viewed'
    )
  ),
  occurred_at timestamptz not null default now(),
  app_version text not null,
  base_version text not null,
  environment text not null,
  device_type text not null check (device_type in ('mobile', 'desktop')),
  selected_count smallint check (selected_count is null or selected_count between 0 and 6),
  pair_count smallint check (pair_count is null or pair_count between 0 and 15),
  compatible_count smallint check (compatible_count is null or compatible_count between 0 and 15),
  incompatible_count smallint check (incompatible_count is null or incompatible_count between 0 and 15),
  variable_count smallint check (variable_count is null or variable_count between 0 and 15),
  no_data_count smallint check (no_data_count is null or no_data_count between 0 and 15),
  alert_count smallint check (alert_count is null or alert_count between 0 and 12),
  created_at timestamptz not null default now()
);

alter table public.usage_events enable row level security;

revoke all on public.usage_events from anon;
revoke all on public.usage_events from authenticated;

-- Sem policies publicas: a app nao le a tabela e nao escreve diretamente nela.
-- A Edge Function usa service role no backend e insere apenas payload validado.
drop policy if exists "usage_events_no_public_select" on public.usage_events;
drop policy if exists "usage_events_no_public_insert" on public.usage_events;

create index if not exists usage_events_event_name_idx
  on public.usage_events (event_name);

create index if not exists usage_events_occurred_at_idx
  on public.usage_events (occurred_at);

create index if not exists usage_events_analysis_idx
  on public.usage_events (occurred_at, device_type)
  where event_name = 'analysis_run';

comment on table public.usage_events is
  'Eventos anonimos/agregados da CompY para relatorio de utilizacao.';
comment on column public.usage_events.event_name is
  'Tipo de evento permitido: app_open, analysis_run, alert_expanded, base_status_viewed.';
comment on column public.usage_events.device_type is
  'Tipo aproximado do dispositivo: mobile ou desktop.';
comment on column public.usage_events.selected_count is
  'Numero agregado de medicamentos selecionados; nao inclui IDs ou nomes.';
comment on column public.usage_events.pair_count is
  'Numero agregado de pares avaliados; nao inclui pares exatos.';

commit;
